server:
  port: 8080
  servlet:
    context-path: /user
  max-http-request-header-size: 8MB

spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: update
      boot:
        allow_jdbc_metadata_access: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${EMAIL}
    password: ${PASS_EMAIL}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

app:
  db:
    init:
      enabled: true
dotenv:
  enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
  hystrix:
    enabled: false
  okhttp:
    enabled: true

jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 3600000000 # in seconds
  refreshable-duration: 3600000 # in seconds




