name: Deploy Java Spring Boot Application To Docker

on:
  push:
    branches:
      - dev_docker_hub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=Devhuynh2003" >> .env
          echo "POSTGRES_DB=identity" >> .env
          echo "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/identity" >> .env
          echo "SPRING_DATASOURCE_USERNAME=postgres" >> .env
          echo "SPRING_DATASOURCE_PASSWORD=Devhuynh2003" >> .env
          echo "PGADMIN_DEFAULT_EMAIL=dacviethuynh@gmail.com" >> .env
          echo "PGADMIN_DEFAULT_PASSWORD=Devhuynh2003" >> .env
          echo "DB_HOST=postgres" >> .env
          echo "DB_PORT=5432" >> .env
          echo "POSTGRES_INITDB_ARGS=--data-checksums" >> .env
          echo "TZ=Asia/Ho_Chi_Minh" >> .env
          echo "MAIL_HOST=smtp.gmail.com" >> .env
          echo "MAIL_PORT=587" >> .env
          echo "EMAIL=dacviethuynh@gmail.com" >> .env
          echo "PASS_EMAIL=rmreuovkyxyjftyl" >> .env
          echo "SIGNER_KEY=1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij" >> .env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: devhuynh2003/user-server:latest